- type: job
  id: Captain
  name: job-name-captain
  description: job-description-captain
  playTimeTracker: JobCaptain
  # begin starcup: command roles are whitelisted
  #requirements:
  #  - !type:DepartmentTimeRequirement
  #    department: Engineering
  #    time: 4h
  #  - !type:DepartmentTimeRequirement
  #    department: Medical
  #    time: 4h
  #  - !type:DepartmentTimeRequirement
  #    department: Science
  #    time: 4h
  #  - !type:DepartmentTimeRequirement
  #    department: Security
  #    time: 4h
  #  - !type:DepartmentTimeRequirement
  #    department: Command
  #    time: 4h
  whitelisted: true
  # end starcup
  weight: 20
  startingGear: CaptainGear
  icon: "JobIconCaptain"
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: CaptainGear
  equipment:
    #shoes: ClothingShoesBootsLaceup # - DeltaV - Commented out for loadout options
    #eyes: ClothingEyesGlassesCommand # starcup: moved to loadouts
    gloves: ClothingHandsGlovesCaptainSyndie # starcup: command recolors
    id: CaptainPDA
    ears: ClothingHeadsetAltCommandSyndie # starcup: command recolors
  storage:
    back:
    - Flash
    # - StationCharter

- type: chameleonOutfit
  id: CaptainChameleonOutfit
  job: Captain
  hasMindShield: true
  equipment:
  # begin starcup: command recolors
    head: ClothingHeadHatCapcapSyndie
    eyes: ClothingEyesGlassesCommandSyndie
    mask: ClothingMaskGasCaptainSyndie
    neck: ClothingNeckCloakCapSyndie
  # end starcup
