- type: job
  id: HeadOfSecurity
  name: job-name-hos
  description: job-description-hos
  playTimeTracker: JobHeadOfSecurity
  # begin starcup: command roles are whitelisted
  # requirements:
  #   - !type:RoleTimeRequirement
  #     role: JobWarden
  #     time: 1h
  #   - !type:RoleTimeRequirement
  #     role: JobDetective
  #     time: 1h # knowing how to use the tools is important
  #   - !type:RoleTimeRequirement
  #     role: JobSecurityOfficer
  #     time: 5h
  #   - !type:DepartmentTimeRequirement
  #     department: Security
  #     time: 10h
  whitelisted: true
  # end starcup
  weight: 10
  startingGear: HoSGear
  icon: "JobIconHeadOfSecurity"
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - HeadOfSecurity
  - Command
  - Brig
  - Security
  - Armory
  - Maintenance
  # - Service # starcup: remove service access from non-service jobs
  - External
  - Detective
  - Cryogenics
  - Brigmedic # starcup
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: HoSGear
  equipment:
    #eyes: ClothingEyesGlassesSecurity # starcup: moved to loadouts
    id: HoSPDA
    gloves: ClothingHandsGlovesCombat
    ears: ClothingHeadsetAltSecurity
  #  pocket1: WeaponPistolMk58Nonlethal # DeltaV - loadouts
  storage:
    back:
    - Flash
  # - MagazinePistol # DeltaV - loadouts

- type: chameleonOutfit
  id: HeadOfSecurityChameleonOutfit
  job: HeadOfSecurity
  hasMindShield: true
  equipment:
    mask: ClothingMaskGasSecurity
    neck: ClothingNeckCloakHos
