- type: job
  id: Warden
  name: job-name-warden
  description: job-description-warden
  playTimeTracker: JobWarden
  requirements:
  # begin starcup
  #   - !type:RoleTimeRequirement
  #     role: JobSecurityOfficer
  #     time: 5h
    - !type:DepartmentTimeRequirement
      department: Security
      time: 2h # starcup: 10h > 2h
  # end starcup
  weight: 5
  startingGear: WardenGear
  icon: "JobIconWarden"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  - Brig
  - Armory
  - Maintenance
  # - Service # starcup: remove service access from non-service jobs
  - External
  - Cryogenics
  - GenpopEnter
  - GenpopLeave
  extendedAccess:
  - Detective # starcup: moved to extended access
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: WardenGear
  equipment:
    #eyes: ClothingEyesGlassesSecurity # starcup: moved to loadouts
    id: WardenPDA
    ears: ClothingHeadsetSecurity
  #  pocket1: WeaponPistolMk58Nonlethal # DeltaV - loadouts
  storage:
    back:
    - Flash
  # - MagazinePistol # DeltaV - loadouts

- type: chameleonOutfit
  id: WardenChameleonOutfit
  job: Warden
  hasMindShield: true
  equipment:
    head: ClothingHeadHatWarden
    mask: ClothingMaskGasSecurity
    outerClothing: ClothingOuterCoatWarden
    jumpsuit: ClothingUniformJumpsuitWarden
    neck: Dinkystar
    belt: ClothingBeltSecurity
    gloves: ClothingHandsGlovesCombat
    shoes: ClothingShoesBootsJack
